version: "2"

services:

    database:
        container_name: database
        image: mariadb:10.3
        restart: always
#        volumes:
#            - ../../database/seedlab:/var/lib/mysql
#            - ./conf/mariadb:/etc/mysql
        environment:
            MYSQL_DATABASE: toto
            MYSQL_USER: toto
            MYSQL_PASSWORD: toto2018
            MYSQL_ROOT_PASSWORD: toto2018

#    adminer:
#        container_name: adminer
#        image: adminer:latest
#        restart: always
#        environment:
#            ADMINER_PLUGINS: 'tables-filter tinymce'
#            ADMINER_DESIGN: 'pepa-linha'
#        ports:
#            - 8011:8080

    composer:
        container_name: composer
        image: composer
#        volumes:
#            - ..:/app
        # Uncomment the line below if you want to run the 'composer update' command when the container starts.
        #command: ["composer", "update"]
        # Comment this line if you don't want to keep container running
        command: "tail -f /dev/null"

    assets:
        container_name: assets
        image: node:alpine
        working_dir: /var/www/assets
        restart: always
#        volumes:
#            - ../public:/var/www/assets
        command: "tail -f /dev/null"

#    mail:
#        container_name: mail
#        image: mailhog/mailhog
#        restart: always
#        ports:
#            - 8025:8025
#            - 1025:1025